/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface WrappedTokenDistributorUpgradeableInterface
  extends ethers.utils.Interface {
  functions: {
    "__WrappedTokenDistributor_initialize(address,address,address)": FunctionFragment;
    "getEstimatedWrappedTokenForUSD(uint256)": FunctionFragment;
    "getPathForUSDToWrappedToken()": FunctionFragment;
    "getSwapRouter()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "__WrappedTokenDistributor_initialize",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEstimatedWrappedTokenForUSD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPathForUSDToWrappedToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapRouter",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "__WrappedTokenDistributor_initialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEstimatedWrappedTokenForUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPathForUSDToWrappedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSwapRouter",
    data: BytesLike
  ): Result;

  events: {
    "DistributedBTC(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DistributedBTC"): EventFragment;
}

export class WrappedTokenDistributorUpgradeable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: WrappedTokenDistributorUpgradeableInterface;

  functions: {
    __WrappedTokenDistributor_initialize(
      swapRouterAddress: string,
      BUSDContractAddress: string,
      WrappedTokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "__WrappedTokenDistributor_initialize(address,address,address)"(
      swapRouterAddress: string,
      BUSDContractAddress: string,
      WrappedTokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getEstimatedWrappedTokenForUSD(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getEstimatedWrappedTokenForUSD(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPathForUSDToWrappedToken(overrides?: CallOverrides): Promise<[string[]]>;

    "getPathForUSDToWrappedToken()"(
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getSwapRouter(overrides?: CallOverrides): Promise<[string]>;

    "getSwapRouter()"(overrides?: CallOverrides): Promise<[string]>;
  };

  __WrappedTokenDistributor_initialize(
    swapRouterAddress: string,
    BUSDContractAddress: string,
    WrappedTokenContractAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "__WrappedTokenDistributor_initialize(address,address,address)"(
    swapRouterAddress: string,
    BUSDContractAddress: string,
    WrappedTokenContractAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getEstimatedWrappedTokenForUSD(
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getEstimatedWrappedTokenForUSD(uint256)"(
    _amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPathForUSDToWrappedToken(overrides?: CallOverrides): Promise<string[]>;

  "getPathForUSDToWrappedToken()"(overrides?: CallOverrides): Promise<string[]>;

  getSwapRouter(overrides?: CallOverrides): Promise<string>;

  "getSwapRouter()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    __WrappedTokenDistributor_initialize(
      swapRouterAddress: string,
      BUSDContractAddress: string,
      WrappedTokenContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "__WrappedTokenDistributor_initialize(address,address,address)"(
      swapRouterAddress: string,
      BUSDContractAddress: string,
      WrappedTokenContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getEstimatedWrappedTokenForUSD(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getEstimatedWrappedTokenForUSD(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPathForUSDToWrappedToken(overrides?: CallOverrides): Promise<string[]>;

    "getPathForUSDToWrappedToken()"(
      overrides?: CallOverrides
    ): Promise<string[]>;

    getSwapRouter(overrides?: CallOverrides): Promise<string>;

    "getSwapRouter()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    DistributedBTC(
      to: string | null,
      amount: null
    ): TypedEventFilter<[string, BigNumber], { to: string; amount: BigNumber }>;
  };

  estimateGas: {
    __WrappedTokenDistributor_initialize(
      swapRouterAddress: string,
      BUSDContractAddress: string,
      WrappedTokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "__WrappedTokenDistributor_initialize(address,address,address)"(
      swapRouterAddress: string,
      BUSDContractAddress: string,
      WrappedTokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getEstimatedWrappedTokenForUSD(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getEstimatedWrappedTokenForUSD(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPathForUSDToWrappedToken(overrides?: CallOverrides): Promise<BigNumber>;

    "getPathForUSDToWrappedToken()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSwapRouter(overrides?: CallOverrides): Promise<BigNumber>;

    "getSwapRouter()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    __WrappedTokenDistributor_initialize(
      swapRouterAddress: string,
      BUSDContractAddress: string,
      WrappedTokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "__WrappedTokenDistributor_initialize(address,address,address)"(
      swapRouterAddress: string,
      BUSDContractAddress: string,
      WrappedTokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getEstimatedWrappedTokenForUSD(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getEstimatedWrappedTokenForUSD(uint256)"(
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPathForUSDToWrappedToken(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPathForUSDToWrappedToken()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSwapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getSwapRouter()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
